export const COUNTRIES = [
  { code: "", label: "All Countries" },
  { code: "us", label: "United States" },
  { code: "gb", label: "United Kingdom" },
  { code: "de", label: "Germany" },
  { code: "fr", label: "France" },
  { code: "it", label: "Italy" },
  { code: "es", label: "Spain" },
  { code: "nl", label: "Netherlands" },
  { code: "pl", label: "Poland" },
  { code: "se", label: "Sweden" },
  { code: "no", label: "Norway" },
  { code: "au", label: "Australia" },
  { code: "ca", label: "Canada" },
  { code: "jp", label: "Japan" },
  { code: "br", label: "Brazil" },
  { code: "in", label: "India" },
  { code: "cn", label: "China" },
  { code: "za", label: "South Africa" },
];
